export const ROUTES = {
  LOGIN: '/iniciar-sesion',
  AUTH_CALLBACK: '/auth/callback',
  HOME: '/',
  CLIENTS: '/clientes',
  CLIENTS_NEW: '/clientes/nuevo',
  CLIENTS_EDIT: (id: number | string) => `/clientes/${id}`,
  PROJECTS: '/proyectos',
  PROJECTS_NEW: '/proyectos/nuevo',
  PROJECTS_DETAIL: (id: number | string) => `/proyectos/${id}`,
  PROJECTS_EDIT: (id: number | string) => `/proyectos/${id}/editar`,
  MEDIA: '/media',
  QUOTES: '/cotizaciones',
  SUPPLIERS: '/proveedores',
  SUPPLIERS_NEW: '/proveedores/nuevo',
  SUPPLIERS_EDIT: (id: number | string) => `/proveedores/${id}`,
  ADMIN_USERS: '/admin/usuarios',
  ADMIN_USERS_NEW: '/admin/usuarios/nuevo',
  ADMIN_USERS_EDIT: (id: number | string) => `/admin/usuarios/${id}`,
  ADMIN_ROLES: '/admin/roles',
  ADMIN_ROLES_NEW: '/admin/roles/nuevo',
  ADMIN_ROLES_EDIT: (id: number | string) => `/admin/roles/${id}`,
  PROFILE: '/perfil',
} as const
